### ISSUE TITLE
Any way to set default config?

### ISSUE THREAD

**Issue by guidoenr** [zhrexl/DrawOnYourScreen2#12]
Hey guys! i'm using this amazing tool in my Kali Linux (cloned from github, not from gnome-extensions) and I would like to know if there is a way to setup a default settings when I start the tool.
And I'm not able to access to the settings screen that the old version has (in gnome-extensions)

In this menu:
- I would like to have something like `3px for default, color: red, line, etc`
![image](https://user-images.githubusercontent.com/47611900/193080669-e7ee4001-9d8e-4efb-81bf-253d286d4717.png)

**Comment by zhrexl** [comment]
I'll close this issue as it is the same as #9. I'll be working on those changes for GNOME v43. I cant guarantee if I'll be able to backport it to older versions.

**Comment by zhrexl** [comment]
I reopened this issue as you gave a better description than others. I'll be working on this now while I'm rethinking the UI.

**Comment by mhewedy** [comment]
For me, I just edited the file `org.gnome.shell.extensions.draw-on-your-screen.gschema.xml` and made the needed changes (in my case I changed the order of the Palette colors), then recompiled the file and it works!

compiled the file with the command:
```shell
glib-compile-schemas draw-on-your-screen2@zhrexl.github.com/schemas/
```

**Comment by Bytezz** [comment]
What about just remembering last used color and size?
Saving them to a dconf every time user change them from menu.

**Comment by zhrexl** [comment]
Its already does it. If its not working check if the settings file was correctly installed.

**Comment by Bytezz** [comment]
I've tried setting color from pink to orange, disabling extension and re-enabling it. When I reopen drawing mode, the color is still the default pink. So it doesn't work for me.

I don't see any relevant setting inside gschema. Where are these saved?
Other settings are working well:
<details>
  <summary>Dconf screenshot</summary>
  
  ![Dconf screenshot 1](https://github.com/zhrexl/DrawOnYourScreen2/assets/25850701/f64358bd-ef0d-45f1-9fb3-1a8672c1c489)

  ![Dconf screenshot 2](https://github.com/zhrexl/DrawOnYourScreen2/assets/25850701/bac05ef8-f1eb-4e24-a8ab-16e69ebb1934)

</details>
