### ISSUE TITLE
Top bar Icon

### ISSUE THREAD

**Issue by Shahin-rmz** [zhrexl/DrawOnYourScreen2#23]
Hello,
thanks for providing useful extension to Gnome.
In 2 in 1 laptops, and it can happen that a user does not want/have to access to keyboard.
so it will be awesome if the extension has active extension on Top Bar.
Thanks

**Comment by zhrexl** [comment]
Same as #19. 
I'll be working on it soon.

**Comment by Shahin-rmz** [comment]
The extension can be used as screenshot extension with draw ability!
