### ISSUE TITLE
Possibility of having transparency / highlighting ?

### ISSUE THREAD

**Issue by wapiflapi** [zhrexl/DrawOnYourScreen2#25]
Hi,

This tool seems great, it was recomended to me for the usecase of drawing on the screen before taking a screenshot.

In this context I would find it super useful to be able to highlight things. While a dedicated highlight tool would be amazing, I think that might not be necessary to get started: I was thinking just being able to use a semi-transparent color would be enough.

Is there anyway of adding a transparent color to the palette ? Any pointers as to how to do this ? If necessary I'm okay making changes in the code to get it to work.

What are the main obstacles to doing this?

Best,

**Comment by zhrexl** [comment]
Unintentionally you just made me realize I wasn't initializing the palettes colors as it was supposed to be.
This is fixed now on version 12.5 (I'll put it on GNOME Extensions today but its already on this repository).

With version 12.5 this is how you do it:
1. Open the extensions settings page 
2. Go to `Drawing Page` tab
3. Click on '+' (which means adding a new palette)
4. You can now close the settings page

5. Open dconf-editor
6. Navigate to `/org/gnome/shell/extensions/draw-on-your-screen/drawing`
7. scroll down til Palettes and click twice on it to edit
![image](https://user-images.githubusercontent.com/51864789/221261492-f20d2711-bb7a-4e95-8e60-431677fbcc76.png)
8. Here you should see a 'New Palette' with 'Black' colors
![image](https://user-images.githubusercontent.com/51864789/221263373-d3d7364a-c34d-490e-8da3-9004828234b0.png)
9. You can edit its name and its color in the following format: `color:name of color` and click on Apply.  Example:
In my  case I changed 'Black' to 'rgba(165,169,45,0.1):Highlight' and this is what I got:
![image](https://user-images.githubusercontent.com/51864789/221264062-5527e765-70e3-42a1-a515-d360ef81ac84.png)


You must remember that while rgb goes from 0 to 255, the alpha parameter is a floating point value that ranges from 0.0 to 1.0.

Finally, IMO all this necessary steps for achieving a simple task as this one is a huge ux flaw in this project. I'll improve it til next week. 

Thanks for reporting. 
I'll keep this issue open until 12.6 is released.

**Comment by zhrexl** [comment]
Now it is possible to edit the palettes on extension settings which makes things a lot simpler.

<img src="https://user-images.githubusercontent.com/51864789/221367711-7270bafe-fa9b-4bae-8c18-2c09e154aa0c.png" height="300">
And then just select your desired color with or without transparency
<img src="https://user-images.githubusercontent.com/51864789/221367948-dc6f9ad3-579e-41a8-88dd-6c44d942fe5b.png" height="300">

**Comment by wapiflapi** [comment]
This is so cool, I never thought I could have this as a feature so quickly, let alone that you would just do it for me :-)

Thank you so much @zhrexl you are amazing :heart:
