### ISSUE TITLE
Not working in Gnome-44

### ISSUE THREAD

**Issue by Vikas-KM** [zhrexl/DrawOnYourScreen2#27]
I was using this on Fedora 37 with Gnome-43, but after upgrading to Fedora-38 with Gnome-44 It stopped working

![image](https://user-images.githubusercontent.com/743498/233447912-378b5e93-8c01-448b-84ba-efb0c928a1c7.png)

**Comment by zhrexl** [comment]
I'm currently on arch linux which has GNOME v43 so I can't test it but the github version is supposed to run on GNOME v44.
As soon as G44 is on arch I'll update it on gnome extensions.

**Comment by Vikas-KM** [comment]
@zhrexl I was using with gnome 43 on Fedora 37 and it was working great, Fedora also doesn't support downgrade, tried but its not working, don't want to reinstall at this point, 
Will wait for your support

**Comment by zhrexl** [comment]
In the meantime you can edit  ````~/.local/share/gnome-shell/extensions/metadata.json```` to include v44 like this:

````"shell-version": [ "42", "43", "44" ]````

**Comment by Vikas-KM** [comment]
Hi Zhrexl,

Thank you very much, I did edit the metadata.json inside the extension (
draw On screen 2) and its working 😊😁😁🙌😍😍


--------------
Regards

Vikas KM

**Comment by zhrexl** [comment]
The new version was sent to GNOME extensions.
Issue closed. If theres a bug please submit a report.

**Comment by e11bits** [comment]
Thanks for making it work with GNOME-44. 🙏
