### ISSUE TITLE
status bar option to activate?

### ISSUE THREAD

**Issue by bksubhuti** [zhrexl/DrawOnYourScreen2#35]
It would be good if there was a way to activate without the keyboard commands.

**Comment by zhrexl** [comment]
It already has.

**Comment by bksubhuti** [comment]
yes.. it does indeed.. new to 23.04 expecting it somewhere else.  Much appreciated.  because flameshot does not work anymore.. this is another way.. please add toobox like flameshot.

**Comment by bksubhuti** [comment]
okay.. i figured out the right click gives pallete.. but i'm not sure you have arrows.. seems like have to manipulate drawings some how..   but good thing.. maybe make a menu for the toolbox to come and then let people know it is right click on that menu

**Comment by deusnovus** [comment]
> i figured out the right click gives pallete

This seriously took me forever to find, I don't know why it's not mentioned in the README page.
