### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by iyagicom** [zhrexl/DrawOnYourScreen2#56]
![image](https://github.com/zhrexl/DrawOnYourScreen2/assets/15052400/2930f6f2-3583-4403-af12-06aad6d85e9c)

what should i do

gnome-shell --version
GNOME Shell 42.9

-Computer-
Processor		: AMD Ryzen 7 5700G with Radeon Graphics
Memory		: 14188MB (2251MB used)
Machine Type		: Desktop
Operating System		: Ubuntu 22.04.3 LTS
User Name		: iyagi (iyagi)
Date/Time		: Sun 07 Jan 2024 05:44:44 AM KST
-Display-
Resolution		: 3440x1440 pixels
OpenGL Renderer		: (Unknown)
X11 Vendor		: The X.Org Foundation
-Audio Devices-
Audio Adapter		: HDA-Intel - HD-Audio Generic
Audio Adapter		: USB-Audio - USB PnP Audio Device(EEPROM)
Audio Adapter		: HDA-Intel - HD-Audio Generic
-Input Devices-
 Power Button
 Power Button
 Video Bus
 USB PnP Audio Device(EEPROM)
 Logitech USB Keyboard
 Logitech USB Keyboard
 MSI MYSTIC LIGHT
 INSTANT USB GAMING MOUSE
 INSTANT USB GAMING MOUSE  Keyboard
 HD-Audio Generic HDMI/DP,pcm:3
 HD-Audio Generic HDMI/DP,pcm:7
 HD-Audio Generic HDMI/DP,pcm:8
 HD-Audio Generic HDMI/DP,pcm:9
 HD-Audio Generic HDMI/DP,pcm:10
 HD-Audio Generic HDMI/DP,pcm:11
 HD-Audio Generic Front Mic
 HD-Audio Generic Rear Mic
 HD-Audio Generic Line
 HD-Audio Generic Line Out Front
 HD-Audio Generic Line Out Surround
 HD-Audio Generic Line Out CLFE
 HD-Audio Generic Front Headphone
-Printers-
No printers found
-SCSI Disks-
ATA Crucial_CT525MX3
VendorCo ProductCode

-Scripting Languages-
Gambas3 (gbr3)		: Not found
Python		: Not found
Python2		: Not found
Python3		: 3.10.12
Perl		: 5.34.0
Perl6 (VM)		: Not found
Perl6		: Not found
PHP		: Not found
Ruby		: Not found
Bash		: 5.1.16(1)-release
-Compilers-
C (GCC)		: Not found
C (Clang)		: Not found
D (dmd)		: Not found
Gambas3 (gbc3)		: Not found
Java		: Not found
CSharp (Mono, old)		: Not found
CSharp (Mono)		: Not found
Vala		: Not found
Haskell (GHC)		: Not found
FreePascal		: Not found
Go		: Not found
-Tools-
make		: Not found
GDB		: (Ubuntu 12.1-0ubuntu1~22.04) 12.1
strace		: 5.16
valgrind		: Not found
QMake		: Not found
CMake		: Not found
Gambas3 IDE		: Not found

-Environment Variables-
GJS_DEBUG_TOPICS		: JS ERROR;JS LOG
USER		: iyagi
XDG_SESSION_TYPE		: wayland
SHLVL		: 0
HOME		: /home/iyagi
DESKTOP_SESSION		: ubuntu
GIO_LAUNCHED_DESKTOP_FILE		: /usr/share/applications/hardinfo.desktop
GTK_MODULES		: gail:atk-bridge
GNOME_SHELL_SESSION_MODE		: ubuntu
MANAGERPID		: 1592
SYSTEMD_EXEC_PID		: 1817
DBUS_SESSION_BUS_ADDRESS		: unix:path=/run/user/1000/bus
GIO_LAUNCHED_DESKTOP_FILE_PID		: 6108
IM_CONFIG_PHASE		: 1
WAYLAND_DISPLAY		: wayland-0
LOGNAME		: iyagi
GTK_IM_MODULE		: uim
_		: /usr/bin/gnome-session
JOURNAL_STREAM		: 8:35752
XDG_SESSION_CLASS		: user
USERNAME		: iyagi
GNOME_DESKTOP_SESSION_ID		: this-is-deprecated
PATH		: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
SESSION_MANAGER		: local/iyagi:@/tmp/.ICE-unix/1776,unix/iyagi:/tmp/.ICE-unix/1776
INVOCATION_ID		: f2abde2ea8ce42afaff50c10c1801a9d
XDG_RUNTIME_DIR		: /run/user/1000
XDG_MENU_PREFIX		: gnome-
GNOME_SETUP_DISPLAY		: :1
DISPLAY		: :0
LANG		: en_US.UTF-8
XDG_CURRENT_DESKTOP		: ubuntu:GNOME
XDG_SESSION_DESKTOP		: ubuntu
XMODIFIERS		: @im=uim
XAUTHORITY		: /run/user/1000/.mutter-Xwaylandauth.TIL6G2
SSH_AGENT_LAUNCHER		: gnome-keyring
SSH_AUTH_SOCK		: /run/user/1000/keyring/ssh
SHELL		: /bin/bash
QT_ACCESSIBILITY		: 1
GDMSESSION		: ubuntu
GJS_DEBUG_OUTPUT		: stderr
QT_IM_MODULE		: uim
PWD		: /home/iyagi
XDG_DATA_DIRS		: /usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
CLUTTER_IM_MODULE		: xim
XDG_CONFIG_DIRS		: /etc/xdg/xdg-ubuntu:/etc/xdg

**Comment by iyagicom** [comment]
i solved
Ubuntu Software then search for and install ‘Extension Manager

**Comment by shugyosha89** [comment]
Extension stopped working after upgrading to Ubuntu 23.10.
![image](https://github.com/zhrexl/DrawOnYourScreen2/assets/59955181/84ec3e5f-450a-4017-b517-8b59e62136b5)

**Comment by zhrexl** [comment]
Old versions of GNOME is not supported anymore. Lack of manpower. Sorry. PR are welcome, as always.
