### ISSUE TITLE
Add gnome-shell 43 compatibility

### ISSUE THREAD

**Issue by somethingGoneWrong** [zhrexl/DrawOnYourScreen2#6]
Hi, can you add gnome 42 compatibility? thx

**Comment by camandel** [comment]
It works on Gnome 42. You just need to add the new version in metadata.js
I opened PR #7

**Comment by zhrexl** [comment]
> It works on Gnome 42. You just need to add the new version in metadata.js I opened PR #7

I fear thats not enough. Gnome shell 42 doesn't have a OsdWindowConstraint anymore.

**Comment by sp1ritCS** [comment]
> I fear thats not enough. Gnome shell 42 doesn't have a OsdWindowConstraint anymore.

the base functionally seems to work. It's just things like the window styles that have changed likely due to the switch to libadwaita. Also GNOME42 new screenshot ui doesn't work with DOYS, as the extensions prevent pressing the button to take a screenshot :/

**Comment by zhrexl** [comment]
> > I fear thats not enough. Gnome shell 42 doesn't have a OsdWindowConstraint anymore.
> 
> the base functionally seems to work. It's just things like the window styles that have changed likely due to the switch to libadwaita. Also GNOME42 new screenshot ui doesn't work with DOYS, as the extensions prevent pressing the button to take a screenshot :/

libadwaita is not a problem, as this extensions uses gtk4 it should not have any compatibility problems. The preference window still works. The screenshot api has changed in gnome and I'll update it. Sadly I'm not finding any documentation about OsdWindows which is making porting this extension a bit harder.
Hope to get it done as soon as possible.

**Comment by sp1ritCS** [comment]
> libadwaita is not a problem, as this extensions uses gtk4 it should not have any compatibility problems. The preference window still works.

it still works, but at least for me there are styling issues with the ListBox(Row)s, which look like they are  libadwaitas fault

**Comment by Julientroploin** [comment]
> It works on Gnome 42. You just need to add the new version in metadata.js I opened PR #7

I tried this and extension can still not be activated, I get this message in GNOME Extensions after logout/login : "class heritage OsdWindow.OsdWindowConstraint is not an object or null"

My metadata.json file :
{ "_generated": "Generated by SweetTooth, do not edit", "data-dir": "draw-on-your-screen", "description": "Start drawing with Super+Alt+D and save your beautiful work by taking a screenshot", "gettext-domain": "draw-on-your-screen", "name": "Draw On Your Screen 2", "persistent-file-name": "persistent", "settings-schema": "org.gnome.shell.extensions.draw-on-your-screen", "shell-version": [ "40", "41", "42" ], "svg-file-name": "DrawOnYourScreen", "url": "https://github.com/zhrexl/DrawOnYourScreen2", "uuid": "draw-on-your-screen2@zhrexl.github.com", "version": 1 }

**Comment by rodrix** [comment]
Hello guys, any news about this? Thanks!

**Comment by zhrexl** [comment]
> Hello guys, any news about this? Thanks!

I've been quite busy this last few weeks writing my thesis. I dont know if I'll be able to work on it before May 20. Sorry for this guys. I am accepting PRs. I'll be working on it after May 20.

**Comment by keithvassallomt** [comment]
For those of you **desperate** to get this working (like me), I've uploaded a version [here](https://sundrybox.s3.eu-central-1.amazonaws.com/draw-on-your-screen2%40zhrexl.github.com.zip) which should work on Gnome 42. Note that this is **Absolutely NOT** a solution to the problem in this thread. This simply edits metadata.json to specify Gnome 42 compatibility, and disables the code which causes the 'OsdWindowConstraint' error when trying to enable the extension.

I will not be submitting a PR since this doesn't solve the problem, it simply ignores it. Maybe this can tide you over until @zhrexl  can fix it properly.

Huge thank you to @zhrexl for forking this extension!

**Comment by keithvassallomt** [comment]
> For those of you **desperate** to get this working (like me), I've uploaded a version [here](https://sundrybox.s3.eu-central-1.amazonaws.com/draw-on-your-screen2%40zhrexl.github.com.zip) which should work on Gnome 42. Note that this is **Absolutely NOT** a solution to the problem in this thread. This simply edits metadata.json to specify Gnome 42 compatibility, and disables the code which causes the 'OsdWindowConstraint' error when trying to enable the extension.
> 
> I will not be submitting a PR since this doesn't solve the problem, it simply ignores it. Maybe this can tide you over until @zhrexl can fix it properly.
> 
> Huge thank you to @zhrexl for forking this extension!

I also noticed that after leaving drawing mode, my keyboard shortcuts (CTRL, META and so on) were not working. I've made another change which **seems** to fix the issue, and have updated the download above.

**Comment by zhrexl** [comment]
> > For those of you **desperate** to get this working (like me), I've uploaded a version [here](https://sundrybox.s3.eu-central-1.amazonaws.com/draw-on-your-screen2%40zhrexl.github.com.zip) which should work on Gnome 42. Note that this is **Absolutely NOT** a solution to the problem in this thread. This simply edits metadata.json to specify Gnome 42 compatibility, and disables the code which causes the 'OsdWindowConstraint' error when trying to enable the extension.
> > I will not be submitting a PR since this doesn't solve the problem, it simply ignores it. Maybe this can tide you over until @zhrexl can fix it properly.
> > Huge thank you to @zhrexl for forking this extension!
> 
> I also noticed that after leaving drawing mode, my keyboard shortcuts (CTRL, META and so on) were not working. I've made another change which **seems** to fix the issue, and have updated the download above.

Thanks for your contribution!

There was a change in [Main.js ](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/7419674bd39b0ac644b3fdb1cb5ba584f20526ee) done by the gnome team that is affecting this extension. I'm working on it. Hope to get a new release soon, thanks guys!

**Comment by sakshamprakash01** [comment]
@zhrexl did you find any solution?

**Comment by zhrexl** [comment]
> @zhrexl did you find any solution?

Yep. The latest commit (from 6 days ago) works on GNOME 42 and can be used sorry not to update you guys. The settings page is not right though. I'll rewrite so it follows LibAdwaita theme. Thats the reason I didnt make a new release. A half done extension is not good enough for a release. Hope to get it(preferences page) done in the next 3~2 days. I'll then do a full review and clean up in the code.

Users should download and manually install the extension from the GNOMEv42 branch until I finish rewriting preferences page.
https://github.com/zhrexl/DrawOnYourScreen2/tree/GNOMEv42

**Comment by aborrell** [comment]
Hi, I'd follow the instructions here but it does not work. I'm running debian Sid with gnome-shell 42.2. When I open the extensions panel it says draw version is not compatble with gnome, I  added _"42"_ in metadata.json, and I've got the following error:
_class heritage OsdWindows:OsdWindowConstraint is not an object or null_

![gnomedraw1](https://user-images.githubusercontent.com/910405/172898745-844bb4c8-fd89-4c30-bbe4-a446ea78446a.png)
 Thanks

**Comment by aborrell** [comment]
Well, with the 42vbranch is working perfectly, thanks for a very useful software

**Comment by 7system7** [comment]
:partying_face: :confetti_ball:

**Comment by xdnroot** [comment]
> For those of you **desperate** to get this working (like me), I've uploaded a version [here](https://sundrybox.s3.eu-central-1.amazonaws.com/draw-on-your-screen2%40zhrexl.github.com.zip) which should work on Gnome 42. Note that this is **Absolutely NOT** a solution to the problem in this thread. This simply edits metadata.json to specify Gnome 42 compatibility, and disables the code which causes the 'OsdWindowConstraint' error when trying to enable the extension.
> 
> I will not be submitting a PR since this doesn't solve the problem, it simply ignores it. Maybe this can tide you over until @zhrexl can fix it properly.
> 
> Huge thank you to @zhrexl for forking this extension!

Your shared file solved my problem, thanks.

**Comment by JaldeaR** [comment]
For Gnome 42 for issue `class heritage OsdWindow.OsdWindowConstraint is not an object or null`
use: https://github.com/zhrexl/DrawOnYourScreen2/tree/GNOMEv42

**Comment by zhrexl** [comment]
I'll close this issue as soon as GNOME v43 support is added.
While this doesnt happen I'd like to ask for your help testing the [libadwaita](https://github.com/zhrexl/DrawOnYourScreen2/tree/libadwaita) branch.

I'd really appreciate your feedback, design and feature requests!

This libadwaita version will be available on GNOME Extensions.

![image](https://user-images.githubusercontent.com/51864789/197406880-9ed2e680-a26e-478b-960c-178948bcda86.png)
![image](https://user-images.githubusercontent.com/51864789/197406965-52b61244-3f1a-4331-a76a-2a4fa5ce736d.png)

Thanks!

**Comment by zhrexl** [comment]
PR #17 closes this issue. The extension was accepted at GNOME extensions.
