### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by jmaibaum** [zhrexl/DrawOnYourScreen2#60]
Hi, GNOME 46 has been released, and, again and unfortunately, there seems to be more to do than "just bump GNOME version in metadata.json". I get:

```
TypeError: (intermediate value).StaticColor is undefined
```

shown in the extensions app. I don't know where to look for more detailed infos though, unfortunately.

**Comment by t0msk** [comment]
+1, its broken in 46

**Comment by cryptbrn** [comment]
this pr should fix the problem https://github.com/zhrexl/DrawOnYourScreen2/pull/61

**Comment by ilker-yilmaz** [comment]
+1, its broken in 46
