### ISSUE TITLE
Broken link to gnome extensions

### ISSUE THREAD

**Issue by schneider8357** [zhrexl/DrawOnYourScreen2#62]
Hello,

The URL https://extensions.gnome.org/extension/4937/draw-on-you-screen-2/ returns 404 not found. Is this an error, or is there an alternative?

Thanks!

**Comment by daniel2pbt** [comment]
I have the same problem

**Comment by zhrexl** [comment]
The extension is not on gnome extensions for now. Will be back soon.

**Comment by daniel2pbt** [comment]
How glad I am to hear that.
Thanks for collaborating on this. This app has helped me a lot

Regards
