### ISSUE TITLE
How to edit color preference and change default palette size?

### ISSUE THREAD

**Issue by xdnroot** [zhrexl/DrawOnYourScreen2#9]
Thanks for make drawOnYourScreen works at Gnome 42. 
However, is there a way to change color instead of using default 9 color?
And how to change default palette size?

**Comment by zhrexl** [comment]
Take a look at this #25.
I think this is solved with v12.6. 
Sorry it took me so long.
If thats not what you meant please reopen this issue.

**Comment by xdnroot** [comment]
Thank you, that was cool. 👍  
However how to change default palette size? Mine still use 5px.
